In [1]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import glob
import matplotlib.pyplot as plt
import seaborn as sns
#import GMM
from statsmodels.sandbox.regression.gmm import GMM, NonlinearIVGMM, LinearIVGMM
import statsmodels.api as sm
#set seaborn graphics
sns.set()
import warnings
warnings.filterwarnings('ignore')

In [2]:
pathdata = os.getcwd()+'/Data'
os.chdir(pathdata)

In [3]:
unr = pd.read_pickle('unr_final.pkl')

In [4]:
for each co

,CurrentYearDiff,OneYearDiff,TwoYearDiff,LongTermDiff,R1,R2
SurveyDate,,,,,,
1999-02-12,3.222750,3.022577,NaN,2.228846,3.130591,3.006950
1999-05-03,-0.184464,-0.263571,NaN,NaN,-0.254706,-0.364600
1999-08-06,-0.170217,-0.258913,NaN,NaN,-0.409524,-0.392308
1999-11-03,-0.089302,-0.213810,NaN,NaN,-0.292000,-0.343421
2000-02-09,-0.884681,-0.863191,NaN,NaN,-0.601163,-0.633810
...,...,...,...,...,...,...
2019-01-11,-0.464147,-0.252860,-0.053252,-0.072339,-0.131739,0.003686
2019-03-22,-0.002696,0.023789,0.051803,-0.021695,0.013512,0.042091
2019-07-05,-0.131175,-0.141900,-0.178422,-0.100325,-0.199660,-0.172548
2019-10-07,-0.031815,0.016300,0.059652,0.049252,-0.035131,0.004888
2020-01-13,-0.125697,-0.063926,-0.043172,-0.065501,0.013124,-0.019699